export const FETCH_HEADER_LINKS_START = 'FETCH_HEADER_LINKS_START';
export const FETCH_HEADER_LINKS_FAILURE = 'FETCH_HEADER_LINKS_FAILURE';
export const FETCH_HEADER_LINKS_SUCCESS = 'FETCH_HEADER_LINKS_SUCCESS';