export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_CURRENT_LOGIN_FORM = 'SET_CURRENT_LOGIN_FORM';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';